CREATE TABLE user (
  id INT PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(85) NOT NULL,
  password VARCHAR(145) NOT NULL
);

CREATE TABLE album (
  id INT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(85) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  user_id INT NOT NULL
);

CREATE TABLE artist (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(85) NOT NULL
);

CREATE TABLE album_artist (
  artist_id INT,
  album_id INT,
  PRIMARY KEY (artist_id, album_id)
);